# Basic
title = "Jacob Bokor"
baseURL = "https://jacobbokor.com/"
theme = "vno-hugo"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10


# fix issue with goldmark rendering engine
[markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmrk.renderer]
      unsafe = true
#    [markup.goldmark.extensions.typographer]
#        apostrophe = '&rsquo;'





# Pagination
paginate = 10
paginatePath = "page"

disableKinds=["sitemap","comment"]

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "https://github.com/0xjmux"
    weight = 10
 [[menu.hidden]]
#    name = "Tags"
    identifier = "Tags"
    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"

[params]
author = "Jacob Bokor"
subtitle = ""
description = "Embedded software engineer, hardware hobbyist, building things enjoyer"
#description = "Embedded software engineer, hardware hobbyist, low-level software enjoyer. Addicted to building."
# Engineer & Student fascinated with embedded systems, low-level software, and everything to do with the hardware-software interface."
welcomeMessage = ""


#### CONFIGURATION

# https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/2



# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "slate"
custom_css = ["css/block.css"]

[params.comment]
disqus = ""
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
#[params.comment.gitalk]
#ID = ""
#secret = ""
#repo = ""
#owner = ""

[params.social]
github = "0xjmux"
twitter = ""
mail = "jacob at jacobbokor dot com"
linkedin = "jacobbokor"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

# https://discourse.gohugo.io/t/hugo-admonitions-a-simple-way-to-add-beautiful-callouts-to-hugo-site/52576/7
[module]
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"

#[permalinks]
#posts = "/:year/:month/:title/"
